name: onlya_english
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  shared_preferences: ^2.3.5
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7
  http: ^1.2.2
  get: ^4.6.6
  random_string: ^2.3.1
  mailer: ^6.3.0
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  flutter_tts: ^4.2.1
  flutter_native_splash: ^2.4.4
  flip_card: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/database/dict_hh.db
    - assets/images/
  uses-material-design: true
